- dockerfiles/itest/itest/Dockerfile.lucid
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/itest.py
- dockerfiles/itest/itest/run_itest.sh
- dockerfiles/lucid/Dockerfile
- dockerfiles/trusty/Dockerfile
- src/debian/changelog
- src/debian/control
- src/setup.py
- src/synapse_tools/configure_synapse.py
The native python yaml parser is _really_ slow, so we should build
against the libyaml-dev package so that we can take advantage of c
bindings if we have them
> Use c yaml bindings

- .gitignore
- .travis.yml
- Makefile
- bintray.json.in
This branch builds itest_trusty with travis, and for tagged versions, pushes the built .deb to [Bintray](https://bintray.com/yelp/paasta/synapse-tools/view).
Similar to Yelp/paasta#337 
Fixes #5
> Public package build

- .gitignore
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/itest.py
- dockerfiles/itest/itest/yelpsoa-configs/service_three/smartstack.yaml
- dockerfiles/itest/itest/yelpsoa-configs/service_two/smartstack.yaml
- src/synapse_tools/configure_synapse.py
- src/synapse_tools/haproxy/qdisc_util.py
- src/tests/configure_synapse_test.py
Added functionality to configure_synapse to create multiple backends for a service (one for each advertise type) and like them to one frontend using  haproxy ACLs.
@solarkennedy @jolynch @jnb
> added backup backends to synapse

- dockerfiles/itest/itest/itest.py
- dockerfiles/itest/itest/run_itest.sh
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
Done in `configure_synapse.py` by injecting a new `bind /var/run/synapse/sockets/%s.sock` line into haproxy.conf.json, to be read by synapse in setting up its haproxy instance.
The tests were updated to reflect this new entry in the 'frontend' section of the generated json. A small helper function was added in the itest to sort lists nested inside dicts. When testing this, I didn't craft the mock json in the same way it was being generated, causing failures due to the differences in list orderings.
Installing this new synapse-tools package will cause /var/run/synapse/sockets/ to be populated with a unix socket for each service, as long as that directory is already created (we'll have to do this in puppet).
Using our internal `proxycurl` based on a recent version of curl, testing these …
> Have haproxy-synapse expose unix sockets for each service

- README.md
The address is a hyphen, not an underscore.
> fix dh-virtualenv link

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
This change adds the ability to specify different default errorfiles in the haproxy-synapse config; it should be entirely optional.
> Adding errorfiles options

- dockerfiles/itest/itest/Dockerfile.lucid
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/Dockerfile.xenial
- dockerfiles/itest/itest/itest.py
- dockerfiles/itest/itest/synapse-tools-both.conf.json
- dockerfiles/itest/itest/synapse-tools-nginx.conf.json
- dockerfiles/trusty/Dockerfile
- dockerfiles/xenial/Dockerfile
- src/debian/changelog
- src/debian/rules
- src/setup.py
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
This depends on [synapse-nginx](https://github.com/jolynch/synapse-nginx) 0.2.2, and allows us to start switching over Smartstack listeners from HAProxy to nginx.
The main contribution here is that we can do the rollout gradually by controlling the "listen_with_X" configuration flags, where we can have just HAProxy bind the listen ports, both HAProxy and nginx bind the listen ports, and just NGINX bind the listen ports.
The integration tests are expanded to test all three listening setups. Integration tests that were better suited for unit tests (testing exact implementation details) were refactored since unit tests cover config generation.
I think I still need to figure out how to make nginx act as a fully transparent proxy (right now it sends back the wrong headers I think), and I need …
> Support NGINX Listening

- dockerfiles/itest/itest/Dockerfile.trusty
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
This addresses the issues with nginx listeners. Specifically:
- Got rid of user directive since we're not launching as root
- Made reloads use the "graceful reload" strategy instead of just HUP. This way new binaries will automatically be picked up
- Cleaned up timeouts to just be the same high value for all listeners (60 minutes since that's or max SS timeout). This means that the only thing we will restart nginx for is new services (this happens basically never)
- Rate limit nginx restarts to once every 10 minutes (since new services rarely happen)
- Try to make the headers less wonky (unfortunately no way to kill Date or Server, but we can at least pass backing Servers forward).
> Fixes for nginx listeners

- src/debian/changelog
- src/setup.py
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
While testing in dev I noticed that we had a bunch of service files being generated for the nginx listeners, which we probably don't want.
> Disable file output on sockets

- dockerfiles/itest/itest/synapse-tools-both.conf.json
- dockerfiles/itest/itest/synapse-tools-nginx.conf.json
- dockerfiles/itest/itest/synapse-tools.conf.json
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
A lot of this is cribbed from [k8ns](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl) and nginx docs on [reverse proxying](https://www.nginx.com/resources/admin-guide/reverse-proxy/) and [websockets](http://nginx.org/en/docs/http/websocket.html). Doing some manual testing indicates that the proper headers are passed now.
I increased the buffers because HAProxy has [16k buffers](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#3.2-tune.bufsize) instead of 8k by default.
proxy_max_temp_file_size is set to 0 to prevent any buffering of responses to files (wth why would you ever do that :-( )
More [sources](https://serverfault.com/questions/768693/nginx-how-to-completely-disable-request-body-buffering).
@jnb @EvanKrall …
> Tries to make NGINX a more proper interactive proxy

- src/debian/changelog
- src/setup.py
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
- src/tox.ini
Some cleanup:
- Synapse was never putting listen_options into listen sections, it was just splitting/duplicating them into frontend/backend sections. For less confusion we just do backend and frontend options
Some new features to support next steps on synapse plugins
- support for state file
- option redispatch -> option redispatch 1 (sneaky way to get allredisp in there)
A new feature because why not
- support for http keep alive (might help ES switch to smartstack load balancing)
> Remove listen options and prepare for the state switch

- .travis.yml
- src/requirements.txt
- src/tox.ini
This also adds xenial to the tests run by travis, but should run in parallel to keep things speedy.
> Fix build for lucid and xenial

- .travis.yml
- Makefile
- README.md
- bintray.json.in
The deploy has been broken since 316010e3, when `bintray.json` was removed from the Makefile, so this adds that functionality back and does per-distribution deploys like done with paasta-tools.
This also switches to use tags for deploys, since we do actually tag releases now (originally changed to master branch in 295c4d7e when tags weren't used for this repo)
> Fix deploy to bintray, use tags, add README badge

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
This makes it the same length as the regular unix socket which is better for consistency and should make it easier to add a length limit to smartstack namespaces.
> Rename the proxy unix socket to be shorter

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
This fixes the issues today we've seen on dev/stage where some Synapses still had the 1024 fd limit (ugh upstart). Always be stop startin.
> Use stop + start instead of restart on Synapse

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
Currently, when multiple services enable the same plugin, the same global option appears multiple times in the HAProxy config, once per service. This change removes replication of plugin options. 
cc @jolynch @jvperrin @matfra
> Remove duplicate plugin options

- src/debian/control
With the upgrade to HAProxy 1.7, we started using the state file, which meant that we have to use the following restart command from synapse:
```
touch {haproxy_pid_file_path} && PID=$(cat {haproxy_pid_file_path}) && (echo show servers state | socat - {haproxy_socket_file_path} > {haproxy_state_file_path} || echo no socket) && {haproxy_path} -f {haproxy_config_path} -p {haproxy_pid_file_path} -sf $PID
```
This has the slight problem of not working when socat isn't installed, so now we do @zareenc
> Depend on socat so that reload commands can use it without fear

- CHANGELOG.md
- dockerfiles/itest/itest/run_itest.sh
- src/synapse_tools/config_plugins/base.py
- src/synapse_tools/config_plugins/fault_injection.py
- src/synapse_tools/config_plugins/logging.py
- src/synapse_tools/config_plugins/path_based_routing.py
- src/synapse_tools/config_plugins/proxied_through.py
- src/synapse_tools/config_plugins/registry.py
- src/synapse_tools/configure_synapse.py
- src/synapse_tools/haproxy/qdisc_tool.py
- src/synapse_tools/haproxy/qdisc_util.py
- src/tests/configure_synapse_test.py
Simply put, this is a fault-injection system at smartstack-level that will allow devs to simulate timeouts at various levels in a multi-service call. The point is, it can allow devs to trigger `RequestBudgetExceededException` on their own or dependent service/s.
Examples:
```
curl -I -v -H'X-Source-Id: spectre-test' -H'Host: internalapi' -H'X-Smartstack-Destination: yelp-main.internalapi' -H'X-Force-Master-Read: True' -H'X-Ctx-Tarpit: spectre.main' 'http://169.254.255.254:20678/category_yelp/?locale=en_US'
```
```
curl -I -v -H'X-Source-Id: spectre-test' -H'Host: internalapi' -H'X-Smartstack-Destination: yelp-main.internalapi' -H'X-Force-Master-Read: True' -H'X-Ctx-Tarpit: spectre.main, yelp-internalapi.main' 'http://169.254.255.254:20678/category_yelp/?locale=en_US'
```
Manually, on my …
> PERF-2836: tarpitting requests

- CHANGELOG.md
- dockerfiles/itest/itest/run_itest.sh
- src/debian/changelog
- src/requirements.txt
- src/setup.py
Trusty boxes don't have this dependency—I should've realized that when I changed the itest. Doh!
Basically, the package generated uses `pkg_resources` and that requires `backports.functools_lru_cache`.
```
---------------------------------------- Captured stderr ----------------------------------------
Traceback (most recent call last):
File "/usr/bin/configure_synapse", line 6, in <module>
from pkg_resources import load_entry_point
File "/opt/venvs/synapse-tools/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
@_call_aside
File "/opt/venvs/synapse-tools/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
f(*args, **kwargs)
File "/opt/venvs/synapse-tools/local/lib/python2.7/site-packages/pkg_resources/__init__.py", …
```
> Add backports.functools_lru_cache as a dependency for synapse-tools

- CHANGELOG.md
- dockerfiles/itest/itest/itest.py
- dockerfiles/itest/itest/yelpsoa-configs/service_three/smartstack.yaml
- dockerfiles/itest/itest/yelpsoa-configs/service_two/smartstack.yaml
- dockerfiles/itest/service_two/test-server.py
- src/debian/changelog
- src/setup.py
- src/synapse_tools/config_plugins/logging.py
- src/synapse_tools/config_plugins/registry.py
- src/synapse_tools/config_plugins/source_required.py
- src/synapse_tools/configure_synapse.py
- src/synapse_tools/lua_scripts/add_source_header.lua
- src/tests/configure_synapse_test.py
It enables a plugin called `source_required`. This, when enabled, will add a `X-Smartstack-Origin` header to the request. The value of this header will be the smartstack namespace of the calling service.
As required by DSWG, it will enable Apollo to identify clients calling it (APOLLO-457).
I've already modified unit tests and added itest to confirm this change. But I am also cutting an rc (which is why the change in `src/setup.py`) and installing it one (or more) devbox test the impact.
> Add X-Smartstack-Origin header for configured services

- CHANGELOG.md
- src/debian/changelog
- src/setup.py
- src/synapse_tools/config_plugins/base.py
- src/synapse_tools/config_plugins/source_required.py
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
`http-request` directives should not be placed before `reqxxx` directives. So, we give plugin authors the ability to prepend plugin directives if required.
> Reorder plugin directives to avoid warnings

- dockerfiles/itest/itest/itest.py
- src/synapse_tools/lua_scripts/add_source_header.lua
Set `X-Smartstack-Origin` to `0` for unidentifiable services to avoid spoofing. This automatically overrides any `X-Smartstack-Origin` that the client may send.
> Pass a 0 as source for unidentifiable services

- src/synapse_tools/configure_synapse.py
Nginx will ignore SIGUSR2 if it's the new master process and its old master has not shut down yet.
This can cause problems: synapse will think it has reloaded nginx to e.g. add a new `server` directive, but nginx has not actually reloaded.
Internal ticket for more context: PAASTA-14538
> Clean up old shutting-down nginx if we need to reload again.

- dockerfiles/itest/itest/itest.py
- src/synapse_tools/lua_scripts/add_source_header.lua
- src/tox.ini
I have added new integration test that, without the fixes I've made in this commit, failed with the same error that we saw in the last go (https://fluffy.yelpcorp.com/i/4Q14JJHcMtPCQgqKhx7tQ4CtsbH5rMG0.html):
```
[ALERT] 295/063605 (89911) : lua init: runtime error: ...packages/synapse_tools/lua_scripts/add_source_header.lua:6: 'new': failed to open pattern file </var/run/synapse/maps/ip_to_service.map>..
```
Now this test passes.
> Make the add_source_header lua plugin more resilient to the absence of the map file

- src/synapse_tools/configure_synapse.py
We reverted the changed that rolled out 0.13.21 everywhere (https://reviewboard.yelpcorp.com/r/315864/). But we haven't really reverted the actual changes in this codebase. As a result, my changes include this DAR-inducing line and error out on 0.13.25.
> Cleaning up the change that caused DAR-396:

- src/synapse_tools/configure_synapse.py
An alternative to the approach I used is to continue using `hash` and se the `PYTHONSEED` to 0 or somethingm. But in Python3, it is recommended to use one of the inbuilt hashlib algos to do deterministic hashing.
> Use deterministic hashing for server_order_seed in python3

- dockerfiles/itest/itest/itest.py
- src/debian/synapse-tools.links
- src/setup.py
- src/synapse_tools/generate_container_ip_map.py
This is
https://github.com/Yelp/paasta/blob/master/paasta_tools/contrib/get_containers_and_ips.py
moved to synapse-tools.
This is to ease the deployment of changes by grouping it with lua_scripts
deployment. It will also help with integration testing with the lua scripts and haproxy.
The script has been renamed to reflect its true purpose, to generate_container_ip_map.
Also, updated the generate_container_ip_map to add timeout argument.
> APOLLO-815: Add generate_container_ip_map

- src/requirements.txt
- src/synapse_tools/config_plugins/base.py
- src/synapse_tools/configure_synapse.py
We run nginx without any kind of error logging. This could potentially
hide issues. I'm investigating a case where requests are not making it
to haproxy so enabling the logs is a first good step here.
This change is a noop as I keep the same default values
I didn't bump pyyaml because the version that contains the fix for the security issue mentioned by github is not stable yet
See https://github.com/yaml/pyyaml/issues/243
> Add error log option

- .travis.yml
When I tagged v0.13.30 and pushed it, travis failed when building the mypy target: [https://travis-ci.org/Yelp/synapse-tools/builds/523617116](https://travis-ci.org/Yelp/synapse-tools/builds/523617116)
There shouldn't be anything to deploy for mypy, so let's make travis ignore it.
I tested the conditional using `travis-conditions`:
```
$ MAKE_TARGET=itest_xenial
$ travis-conditions eval "$MAKE_TARGET =~ ^itest_" --data '{}'
true
$ MAKE_TARGET=itest_trusty
$ travis-conditions eval "$MAKE_TARGET =~ ^itest_" --data '{}'
true
$ MAKE_TARGET=mypy
$ travis-conditions eval "$MAKE_TARGET =~ ^itest_" --data '{}'
false
```
> Ignore mypy when deploying

- src/requirements.txt
Bump `pyyaml` to 4.2b1 because of the security alert.
> Bump pyyaml version because of the security alert

- .gitignore
- .travis.yml
- dockerfiles/bionic/Dockerfile
- dockerfiles/bionic/docker-compose.yml
- dockerfiles/itest/docker-compose-bionic.yml
- dockerfiles/itest/itest/Dockerfile.bionic
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/Dockerfile.xenial
- dockerfiles/itest/itest/zookeeper_discovery/infrastructure/local.yaml.bionic
- dockerfiles/itest/service_one/Dockerfile
- dockerfiles/itest/service_three/Dockerfile
- dockerfiles/itest/service_two/Dockerfile
- dockerfiles/itest/zookeeper/Dockerfile
- dockerfiles/trusty/Dockerfile
- dockerfiles/xenial/Dockerfile
- src/tox.ini
- tox.ini
This is SMTSTK-228, but essentially I'm just adding the itests, dockerfiles, and general setup for building and testing this with bionic. None of the actual package code changes, just the testing infrastructure.
I also upgraded the nginx version used for trusty from `1.11.10` to `1.13.3` to match bionic (and the version we are using), and had to custom-built the nginx version in bionic to avoid an issue where the upstream nginx version uses `--with-stream=dynamic` but we use `--with-stream` meaning the config would be different between the itest and reality (and just for bionic too), so I thought building nginx in the container was the easiest and most consistent way out of that one.
> Build for bionic

- src/synapse_tools/config_plugins/base.py
- src/synapse_tools/configure_synapse.py
Introduce `nginx_reload_script` configuration option, allowing to
specify a script which will be used to reload `nginx`.
Change the existing actions in such a way that while reloading `nginx`,
after we sent `SIGUSR2` to `nginx` asking it to launch a new instance of
itself, let's check that the new instance actually launched before
killing the old one.
> Reload nginx really gracefully

- src/requirements.txt
We've changed some kubernetes labels and need to make sure nothing reads the old ones.
> Bump paasta to 0.90.4

- src/debian/rules
Tests are failing with errors like
```
Traceback (most recent call last):
File
"/work/src/debian/synapse-tools/opt/venvs/synapse-tools/lib/python3.6/site-packages/pip_custom_platform/_main.py",
line 15, in <module>
from pip._internal.commands import get_summaries
ImportError: cannot import name 'get_summaries'
```
because of a changed `_internals` in `pip==20.1b1`.
Let's fix that by using `pip==19.3.1`.
`itest_trusty` is broken because of python2, broken versions of several core python libraries, and several other things.
Since we're moving from Trusty, I'm not going to fix it, but going to disable it in the following PR.
> Fix tests by downgrading pip to 19.3.1

- .travis.yml
It's broken and we shouldn't waste our time on fixing it.
> Remove itest_trusty from Travis tests list

- .travis.yml
- Makefile
- dockerfiles/bionic/Dockerfile
- dockerfiles/bionic/docker-compose.yml
- dockerfiles/itest/docker-compose-bionic.yml
- dockerfiles/itest/docker-compose-trusty.yml
- dockerfiles/itest/docker-compose-xenial.yml
- dockerfiles/itest/itest/Dockerfile.bionic
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/Dockerfile.xenial
- dockerfiles/itest/service_one/Dockerfile
- dockerfiles/itest/service_three/Dockerfile
- dockerfiles/itest/service_two/Dockerfile
- dockerfiles/trusty/Dockerfile
- dockerfiles/trusty/docker-compose.yml
- dockerfiles/xenial/Dockerfile
- dockerfiles/xenial/docker-compose.yml
- src/debian/rules
- src/requirements.txt
- tox.ini
Mostly for security reasons we don't want to build from public pypi
internally. We do want to use it for travis of course. Had to update
docker compose to make it pass a build arg. Copy paste of approach in
https://github.com/Yelp/nerve-tools/pull/76
> Ensure internal yelp builds use internal pypi

- dockerfiles/itest/itest/Dockerfile.bionic
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/Dockerfile.xenial
It appears that Travis is either blocked by haproxy.org or is blocking it itself:
https://travis-ci.community/t/access-to-external-git-repo-not-possible-anymore/8975
Let's switch to a re-hosted version of the same tarball to fix this.
> Fix build by rehosting haproxy-1.7.8.tar.gz

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
Internal ticket: MESH-914
This PR teaches configure_synapse how to respect a `envoy_migration.yaml` config file, which has a format like this:
```yaml
migration_enabled: {true|false}
namespaces:
{namespace}:
state: {synapse|dual|envoy}
```
When a namespace is unconfigured or in `synapse` or `dual` state, synapse will configure an haproxy listener on that port just as it usually does. When a namespace is in `envoy` state, no listener will be configured on that port, but synapse will continue to populate the discovery JSON files (the files under `/run/synapse/services`).
* Existing tests pass
* Added some new tests
* Manually installed and tested on a Yelp devbox; internal users can inspect a diff of the synapse config [here](https://fluffy.yelpcorp.com/i/XshJLKrb3qNSs2rNbCFrG9pFMlnfbSSJ.htm …
> Add envoy migration toggles to allow disabling haproxy on a per-namespace basis

- .gitignore
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
Internal ticket: MESH-931
The current behavior is to disable both the haproxy and nginx listener when a namespace is Envoy-only. There's a race condition when disabling a namespace where haproxy (the service that listens on a UNIX socket) reloads before nginx (the service that listens on the proxy port and proxies to haproxy) which results in 503s being served for about 10 seconds:
```
$ curl localhost:20139
<html>[...]
$ curl localhost:20139
503 Service Unavailable
Served by haproxy-synapse on 10-65-79-67-useast1aprod.useast1-prod.yelpcorp.com.
$ curl localhost:20139
503 Service Unavailable
Served by haproxy-synapse on 10-65-79-67-useast1aprod.useast1-prod.yelpcorp.com.
$ curl localhost:20139
curl: (7) Failed to connect to localhost port 20139: Connection refused
```
This is bad because …
> Only disable the nginx listener when a namespace is Envoy-only

- src/debian/changelog
- src/setup.py
- src/synapse_tools/generate_container_ip_map.py
Part of kubelet's lifecycle involves `systemctl restart` on certain
updates.  This makes the local kubelet api unavailable, and the generate
ip mapping script will write an empty map file.
This involves two changes:
1. split mesos and k8s instance discovery funtions, since previously the
function decided "error from k8s api => we're on a mesos box". Now, a
--k8s flag will tell the script to use k8s instance discovery, otherwise
it will default to mesos
2. do not take any further action if the kubelet api returns an error on
a k8s host
rollout for this change will require bumping the package at the same time as adding the `--k8s` flag on kube hosts
> don't write an empty ip map if the kubelet api returns an error

- dockerfiles/itest/itest/srv-configs/service_mesh/envoy_migration.yaml
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
Internal ticket: MESH-862
Using the same config namespace as #86, this PR adds a `reuseport_enable` option that will configure all nginx listeners to use the SO_REUSEPORT socket option.
```yaml
migration_enabled: {true|false}
reuseport_enabled: {true|false}
namespaces:
{namespace}:
state: {synapse|dual|envoy}
```
The new option respects the existing `migration_enable` option as a "master kill switch", meaning if `migration_enable` is False, then SO_REUSEPORT will never be used.
* Existing tests pass
* Added assert statements to verify the existence of the `reuseport` option in nginx listeners
* Added tests to cover the permutations of `migration_enabled` and `reuseport_enabled`
> Add reuseport_enable toggle option for nginx listeners

- dockerfiles/bionic/docker-compose.yml
- dockerfiles/xenial/docker-compose.yml
- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
- src/tox.ini
See ticket acceptance criteria.
This piggybacks on /nail/srv/configs/service_mesh/envoy_migration.yaml by introducing a toggle to control synapse writing service registrations to /var/run/synapse/services.
Testing done:
- cd src && tox --> green
- make itest_xenial --> green
- install package on local box and manually test scenarios:
- config with no registration_writer key
- config with registration_writer=synapse
- config with registration_writer=meshd
> MESH-947 - add toggle for writing service registrations

- src/debian/synapse-tools.links
- src/setup.py
- src/synapse-tools-reload-nginx.sh
- src/synapse_tools/configure_synapse.py
During reload `synapse-tools` restarts `nginx` gracefully, which means
that after the restart the new `nginx` instance accepts new connections, but
the old `nginx` instance exists until all previously established connections are alive.
Since we have some long-running connections, the old instances could run
for very long time.
The issue with that is that `nginx` doesn't restart the second time if
the old instance is still alive.
This PR fixes that by force-killing the old instance before doing the
`nginx` restart.
While here I've also moved all reload logic into a script.
> Fix nginx reload doesn't work second time

- src/synapse_tools/configure_synapse.py
- src/tests/configure_synapse_test.py
if a namespace is not defined on envoy_migration.yaml, let's default to Envoy instead of Synapse.
> MESH-1010 Default to Envoy mode

- Makefile
The test target is expected by internal CI processes.
> Add noop test target
